MIR24/mir24-deploy

- .gitignore
- README.md
- deploy.php
- hosts.yml
hosts.yml fix and some local deployment improvements
> custom-local-deploy

- deploy.php
- hosts.yml
https://mir24tv.atlassian.net/browse/MIRSCR-962
> MIRSCR-962 BC component solo depployment fix

- deploy.php
- hosts.yml
- recipe/laravel.php
1. laravel recipe override to solve "Not a git repo error"
2. removed hardcoded dbname
3. code refactoring
> Deploy fixes

- deploy.php
- hosts.yml
- recipe/sphinx.php
Добавлены таски для Sphinx (отдельный файл)
Но пока не выбран момент для запуска indexer
> MIRSCR-952 sphinx settings

- deploy.php
- hosts.yml
- recipe/db.php
Таски для БД вынесены в отдельный файл
Добавлен пользователь для администрирования БД
> MIRSCR-971 DB configuration 

- deploy.php
https://mir24tv.atlassian.net/browse/MIRSCR-973
> MIRSCR-973 rsync added for prod hosts

- deploy.php
1) BC и PB теперь используют npm таски
2) tsd запускается локально
3) Переписан таск rsync для работы на удаленном хосте
> BC-PB-fixes

- deploy.php
- hosts.yml
- recipe/db.php
- recipe/sphinx.php
1) Конфиг БД в sphinx.conf
2) Реиндексация sphinx после деплоя
> DB and sphinx

- deploy.php
- hosts.yml
Добавлены таски для хотфиксов, исправлен rsync
> hotfix-tasks

- recipe/db.php
https://mir24tv.atlassian.net/browse/MIRSCR-999
> MIRSCR-999 branch for db repo

- hosts.yml
- recipe/db.php
Возможность указать отдельную ветку для БД
Фикс для Rsync (чтобы не терять папку PB)
> Db clone modified, fixed rsync for local deploy

- hosts.prod.yml.example
- hosts.yml
https://mir24tv.atlassian.net/browse/MIRSCR-1055
> MIRSCR-1055 sitemap dir fix

- README.md
- deploy.php
- hosts.prod.example.yml
- hosts.yml
- recipe/db.php
Изменен порядок работы с БД. 
Теперь один и тот же таск для наполнения БД используется как для тестовой, так и для рабочей сборки.
Добавлен параметр `db_source_mode`, который регулирует источник данных для БД релиза.
`db_name_releasing` переименован в `db_app_name`, чтобы упростить workflow и унифицировать названия параметров для работы с БД.
> MIRSCR-1063 DB flow

- README.md
- recipe/db.php
https://mir24tv.atlassian.net/browse/MIRSCR-1070
Добавлено описание двухстадийной сборки в readme.
Исправлен параметр `db_name_previous`, чтобы команда `db:repipe` могла работать отдельно.
> MIRSCR-1070 Two stage build fixed

- deploy.php
- recipe/db.php
Внесены изменения в процесс в связи с тем, что database переносится в backend-server
> Deploy database operations flow changed

- deploy.php
- hosts.prod.example.yml
- hosts.yml
- recipe/db.php
1. Добавлены роли для компонент. Теперь фильтрация тасков осуществляется на основе ролей, тем самым устранена жесткая привязка к названию хоста.
1. Изменена работа с параметром `stage`. Возможные варианты: dev, test, prod. Для локальной разработки, тестирования и продакшн среды соответственно.
1. Изменен таск `sphinx:inject` для более корректного взаимодействия хостов
1. В hosts.yml теперь используется общий базовый путь. Это упрощает настройку deployer-а через ansible.
> Tasks roles filter

- deploy.php
https://mir24tv.atlassian.net/browse/MIRSCR-1098
Процесс деплоя упрощен с учетом изменений в gulpfile.js frontend-server.
> MIRSCR-1098 gulp workflow simplified

- deploy.php
- hosts.prod.example.yml
- hosts.yml
- recipe/laravel.php
https://mir24tv.atlassian.net/browse/MIRSCR-1082
Админка переводится в maintenance режим при деплое.
> MIRSCR-1082 artisan down on deploy

- .gitignore
- deploy.php
- templates/hosts.dev.yml
- templates/hosts.prod.yml
https://mir24tv.atlassian.net/browse/ST-981
> Release 0.22

- hosts.yml
https://mir24tv.atlassian.net/browse/MIRSCR-1120
Добавлены параметры для настройки гугл-аналитики
> MIRSCR-1120 env params

- hosts.yml
https://mir24tv.atlassian.net/browse/MIRSCR-1198
> MIRSCR-1198 writable dirs expanded

- deploy.php
- hosts.yml
- templates/hosts.prod.yml
https://mir24tv.atlassian.net/browse/MIRSCR-1145
> MIRSCR-1145 Date format changed for release and DB

- deploy.php
- hosts.yml
Добавлена работа с env файлом для photobank-client
> Flow fixes

- .gitignore
- deploy.php
- templates/hosts.dev.yml
- templates/hosts.prod.yml
https://mir24tv.atlassian.net/browse/MIRSCR-1111
Добавлена очистка таблицы `snatches` в процессе деплоя
> MIRSCR-1111 snatches table truncating

- deploy.php
> Revert "Release 0.36"

- deploy.php
https://mir24tv.atlassian.net/browse/MIRSCR-1298
> MIRSCR-1298-clear-cache-after-deploy

- deploy.php
- hosts.yml
- templates/hosts.prod.yml
> Revert "Mirscr 1069. Конфигурирование supervisord средствами deployer"

- .env.backend
- .env.frontend
- hosts.yml
- templates/hosts.prod.yml
https://mir24tv.atlassian.net/browse/MIRSCR-1364
> MIRSCR-1364-referrer-in-vast-tag. Change VIDEO_VAST_TAG

- deploy.php
- hosts.yml
- templates/hosts.prod.yml
https://mir24tv.atlassian.net/browse/MIRSCR-1268
https://github.com/MIR24/mir24tv-service-scripts/pull/26/files
> MIRSCR-1268-cron-to-git. Add task cron:clone

- deploy.php
https://mir24tv.atlassian.net/browse/MIRSCR-1421
> MIRSCR-1421-escaping-in-env. Add double quotes

- .env.backend
- .env.frontend
- hosts.yml
https://mir24tv.atlassian.net/browse/MIRSCR-1426
> MIRSCR-1426-table-cache-list-in-hosts-yaml

- hosts.yml
- templates/hosts.dev.yml
- templates/hosts.prod.yml
https://mir24tv.atlassian.net/browse/MIRSCR-1437
> MIRSCR-1437-composer-install
